version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - |
        echo "[install] runtime check"
        java -version
        node -v
        npm -v

  build:
    commands:
      - |
        echo "[build] repo root"
        if [ -d "book_management" ]; then cd book_management; fi
        WORKDIR="$(pwd)"
        echo "WORKDIR=${WORKDIR}"
        ls -la

        echo "[build] detect backend dir"
        BACKEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name gradlew -print -quit)")"
        if [ -z "${BACKEND_DIR}" ] || [ "${BACKEND_DIR}" = "." ]; then
          BACKEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name build.gradle -print -quit)")"
        fi
        if [ -z "${BACKEND_DIR}" ] || [ "${BACKEND_DIR}" = "." ]; then
          BACKEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name pom.xml -print -quit)")"
        fi
        echo "BACKEND_DIR=${BACKEND_DIR}"

        if [ -z "${BACKEND_DIR}" ] || [ ! -d "${WORKDIR}/${BACKEND_DIR}" ]; then
          echo "ERROR: backend directory not found"
          exit 2
        fi

        echo "[build] backend build"
        cd "${WORKDIR}/${BACKEND_DIR}"
        ls -la

        if [ -f "./gradlew" ]; then
          echo "Use Gradle Wrapper"
          chmod +x ./gradlew
          ./gradlew --no-daemon clean test build
        elif command -v gradle >/dev/null 2>&1; then
          echo "Use system gradle"
          gradle clean test build
        elif [ -f "./mvnw" ]; then
          echo "Use Maven Wrapper"
          chmod +x ./mvnw
          ./mvnw -B test package
        elif command -v mvn >/dev/null 2>&1; then
          echo "Use system mvn"
          mvn -B test package
        else
          echo "ERROR: no gradle/maven tool found. Add wrapper to repo."
          exit 3
        fi

        echo "[build] detect frontend dir (package.json)"
        cd "${WORKDIR}"
        FRONTEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name package.json -not -path '*/node_modules/*' -print -quit)")"
        echo "FRONTEND_DIR=${FRONTEND_DIR}"

        if [ -z "${FRONTEND_DIR}" ] || [ ! -d "${WORKDIR}/${FRONTEND_DIR}" ]; then
          echo "ERROR: frontend directory not found"
          exit 4
        fi

        echo "[build] frontend build"
        cd "${WORKDIR}/${FRONTEND_DIR}"
        npm ci
        npm run build

        echo "[build] collect artifacts"
        cd "${WORKDIR}"
        mkdir -p artifact/backend artifact/frontend

        echo "[build] backend jar/war (optional)"
        BACK_ART_PATH="$(find "${WORKDIR}/${BACKEND_DIR}" -maxdepth 10 -type f \( -name "*.jar" -o -name "*.war" \) \
          -not -path "*/.gradle/*" -not -path "*/gradle/wrapper/*" -print -quit)"
        echo "BACK_ART_PATH=${BACK_ART_PATH}"
        if [ -n "${BACK_ART_PATH}" ]; then
          cp "${BACK_ART_PATH}" artifact/backend/
        else
          echo "[warn] backend jar/war not found. Copy build/target outputs."
          if [ -d "${WORKDIR}/${BACKEND_DIR}/build" ]; then
            mkdir -p artifact/backend/build_output
            cp -r "${WORKDIR}/${BACKEND_DIR}/build" artifact/backend/build_output/
          fi
          if [ -d "${WORKDIR}/${BACKEND_DIR}/target" ]; then
            mkdir -p artifact/backend/build_output
            cp -r "${WORKDIR}/${BACKEND_DIR}/target" artifact/backend/build_output/
          fi
        fi

        echo "[build] frontend output auto-detect by index.html"
        FRONT_ROOT="${WORKDIR}/${FRONTEND_DIR}"
        echo "FRONT_ROOT=${FRONT_ROOT}"

        # 1) index.html 찾기 (Angular/React/Vite 대부분)
        INDEX_HTML="$(find "${FRONT_ROOT}" -maxdepth 6 -type f -name index.html -not -path "*/node_modules/*" -print -quit)"
        echo "INDEX_HTML=${INDEX_HTML}"

        if [ -n "${INDEX_HTML}" ]; then
          OUT_DIR="$(dirname "${INDEX_HTML}")"
          echo "FRONT_OUT_DIR=${OUT_DIR}"
          cp -r "${OUT_DIR}" artifact/frontend/
        else
          # 2) 그래도 없으면 dist/build/out 후보 디렉터리 찾기
          OUT_DIR="$(find "${FRONT_ROOT}" -maxdepth 4 -type d \( -name dist -o -name build -o -name out \) -not -path "*/node_modules/*" -print -quit)"
          echo "FRONT_OUT_DIR_FALLBACK=${OUT_DIR}"
          if [ -n "${OUT_DIR}" ]; then
            cp -r "${OUT_DIR}" artifact/frontend/
          else
            echo "ERROR: frontend output not found (no index.html, no dist/build/out). Dump frontend root:"
            ls -la "${FRONT_ROOT}" || true
            exit 6
          fi
        fi

        echo "COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION}" > artifact/BUILD_INFO.txt
        echo "BACKEND_DIR=${BACKEND_DIR}" >> artifact/BUILD_INFO.txt
        echo "FRONTEND_DIR=${FRONTEND_DIR}" >> artifact/BUILD_INFO.txt

artifacts:
  files:
    - artifact/**/*
  discard-paths: no
