version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - |
        echo "[install] runtime check"
        java -version
        node -v
        npm -v

  build:
    commands:
      - |
        set -e

        echo "[build] repo root"
        WORKDIR="$(pwd)"
        echo "WORKDIR=${WORKDIR}"
        ls -la

        echo "[build] backend build: backend/demo"
        cd "${WORKDIR}/backend/demo"
        chmod +x ./gradlew
        ./gradlew --no-daemon clean test build

        echo "[build] frontend build: frontend"
        cd "${WORKDIR}/frontend"

        if [ ! -f "package.json" ]; then
          echo "ERROR: frontend/package.json not found"
          exit 10
        fi

        node -e "const p=require('./package.json'); if(!p.scripts||!p.scripts.build){console.error('ERROR: Missing script: build'); process.exit(11)}"

        npm ci
        npm run build

        echo "[build] collect artifacts"
        cd "${WORKDIR}"
        rm -rf artifact
        mkdir -p artifact/backend artifact/frontend

        # backend jar
        if ls backend/demo/build/libs/*.jar >/dev/null 2>&1; then
          cp backend/demo/build/libs/*.jar artifact/backend/
        else
          echo "ERROR: jar not found under backend/demo/build/libs"
          ls -la backend/demo/build || true
          exit 12
        fi

        # frontend output (common)
        FRONT_OUT=""
        for d in dist build out .next .output storybook-static; do
          if [ -d "frontend/${d}" ]; then
            FRONT_OUT="frontend/${d}"
            break
          fi
        done

        echo "FRONT_OUT=${FRONT_OUT}"
        if [ -z "${FRONT_OUT}" ]; then
          echo "ERROR: frontend output dir not found (dist/build/out/.next/.output/...)"
          ls -la frontend || true
          exit 13
        fi

        cp -r "${FRONT_OUT}" artifact/frontend/

        echo "COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION}" > artifact/BUILD_INFO.txt

artifacts:
  files:
    - artifact/**/*
  discard-paths: no
