version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "[install] runtime check"
      - java -version
      - node -v
      - npm -v

  build:
    commands:
      - echo "[build] repo root"
      - WORKDIR="$(pwd)"
      - echo "WORKDIR=${WORKDIR}"
      - ls -la

      # -------------------------
      # Backend (fixed path)
      # -------------------------
      - echo "[build] backend build (backend/demo)"
      - cd "${WORKDIR}/backend/demo"
      - ls -la
      - chmod +x ./gradlew
      - ./gradlew --no-daemon clean test build

      # -------------------------
      # Frontend (fixed path)
      # -------------------------
      - echo "[build] frontend build (frontend)"
      - cd "${WORKDIR}/frontend"
      - test -f package.json || (echo "ERROR: frontend/package.json not found" && exit 10)
      - npm ci
      - npm run build

      # -------------------------
      # Collect artifacts
      # -------------------------
      - echo "[build] collect artifacts"
      - cd "${WORKDIR}"
      - mkdir -p artifact/backend artifact/frontend

      # backend jar
      - JAR_PATH="$(ls -1 backend/demo/build/libs/*.jar | head -n 1)"
      - echo "JAR_PATH=${JAR_PATH}"
      - test -n "${JAR_PATH}" || (echo "ERROR: jar not found under backend/demo/build/libs" && exit 11)
      - cp "${JAR_PATH}" artifact/backend/

      # frontend output (common frameworks)
      - FRONT_OUT=""
      - for d in dist build out .next .output storybook-static; do if [ -d "frontend/${d}" ]; then FRONT_OUT="frontend/${d}"; break; fi; done
      - echo "FRONT_OUT=${FRONT_OUT}"
      - test -n "${FRONT_OUT}" || (echo "ERROR: frontend output dir not found (dist/build/out/.next...)" && ls -la frontend && exit 12)
      - cp -r "${FRONT_OUT}" artifact/frontend/

      - echo "COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION}" > artifact/BUILD_INFO.txt

artifacts:
  files:
    - artifact/**/*
