version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - |
        set -e
        echo "[install] runtime check"
        java -version
        node -v
        npm -v

  pre_build:
    commands:
      - |
        set -e
        echo "[pre_build] normalize repo root"
        if [ -d "book_management" ]; then
          cd book_management
        fi

        WORKDIR="$(pwd)"
        echo "WORKDIR=${WORKDIR}"
        ls -la

        echo "[pre_build] detect backend dir (gradlew/build.gradle)"
        BACKEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name gradlew -print -quit)")"
        if [ -z "${BACKEND_DIR}" ] || [ "${BACKEND_DIR}" = "." ]; then
          BACKEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name build.gradle -print -quit)")"
        fi
        echo "BACKEND_DIR=${BACKEND_DIR}"

        echo "[pre_build] detect frontend dir (package.json)"
        FRONTEND_DIR="$(dirname "$(find . -maxdepth 6 -type f -name package.json -not -path '*/node_modules/*' -print -quit)")"
        echo "FRONTEND_DIR=${FRONTEND_DIR}"

        # 다음 phase에서도 쓰기 위해 파일로 export 저장
        echo "export WORKDIR='${WORKDIR}'" > /tmp/envvars
        echo "export BACKEND_DIR='${BACKEND_DIR}'" >> /tmp/envvars
        echo "export FRONTEND_DIR='${FRONTEND_DIR}'" >> /tmp/envvars
        cat /tmp/envvars

  build:
    commands:
      - |
        set -e
        . /tmp/envvars

        echo "[build] backend"
        if [ -z "${BACKEND_DIR}" ] || [ ! -d "${WORKDIR}/${BACKEND_DIR}" ]; then
          echo "ERROR: backend directory not found"
          exit 2
        fi

        cd "${WORKDIR}/${BACKEND_DIR}"
        if [ ! -f "./gradlew" ]; then
          echo "ERROR: gradlew not found in ${WORKDIR}/${BACKEND_DIR}"
          ls -la
          exit 3
        fi
        chmod +x ./gradlew
        ./gradlew --no-daemon clean test bootJar

        echo "[build] frontend"
        cd "${WORKDIR}"
        if [ -z "${FRONTEND_DIR}" ] || [ ! -d "${WORKDIR}/${FRONTEND_DIR}" ]; then
          echo "ERROR: frontend directory not found"
          exit 4
        fi

        cd "${WORKDIR}/${FRONTEND_DIR}"
        npm ci
        npm run build

  post_build:
    commands:
      - |
        set -e
        . /tmp/envvars

        echo "[post_build] collect artifacts"
        cd "${WORKDIR}"
        mkdir -p artifact/backend artifact/frontend

        JAR_PATH="$(find "${WORKDIR}/${BACKEND_DIR}/build/libs" -maxdepth 1 -type f -name "*.jar" -print -quit)"
        if [ -z "${JAR_PATH}" ]; then
          echo "ERROR: jar not found under build/libs"
          ls -la "${WORKDIR}/${BACKEND_DIR}/build/libs" || true
          exit 5
        fi
        cp "${JAR_PATH}" artifact/backend/

        if [ -d "${WORKDIR}/${FRONTEND_DIR}/dist" ]; then
          cp -r "${WORKDIR}/${FRONTEND_DIR}/dist" artifact/frontend/
        else
          echo "ERROR: dist not found"
          ls -la "${WORKDIR}/${FRONTEND_DIR}" || true
          exit 6
        fi

        echo "COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION}" > artifact/BUILD_INFO.txt

artifacts:
  files:
    - artifact/**/*
  discard-paths: no
